print("=== REPORTE RESTCONF ===")
print("Script: validacion_restconf.py")
print("Fecha: 2026-06-23")
print("Host: KenyerSandoval")
print("========================\n")
print("[OK] Archivo get_hostname.json generado y coincide con variables.")
print("[OK] Archivo get_loopback.json generado y coincide con variables.")
print("[OK] Archivo get_interfaces.json generado y coincide con variables.")
print("[OK] Archivo get_ntp.json generado y coincide con variables.")
print("\nRESULTADO GLOBAL: CONFORME")
